//
// Created by tang on 19-3-18.
//

#ifndef LEPTSERVER_LEPTDEFINITION_H
#define LEPTSERVER_LEPTDEFINITION_H

#define LEPTSERVER_VERSION "0.1"  // 程序版本

#define MAXLINE 2014

#define MAXBUF 8196

#define THREADNUMS 4

#define PORTNUMBER "8080"

#define MAXEVENTS 1024

#define LISTENQ 1024

#define HTTP_OK 200

#define HTTP_NOT_MODIFIED 304

#define HTTP_NOT_FOUND 404

#define DEFAULT_TIMEOUT 500  /* ms */

#define WORKDIR "/home/tang/CLionProjects/LeptServer"

enum SHUTDOWN_T
{
    GRACEFUL_SHUTDWON,
    IMMEDIATE_SHUTDOWN
};

enum HTTP_PARSE_REQUEST_LINE_STATE_T  // 解析http请求行时的状态
{
    LINE_START,

    METHOD,
    SPACE_BEFORE_URI,
    SLASH_IN_URI,
    SPACE_BEFORE_HTTP,
    HTTP_H,
    HTTP_HT,
    HTTP_HTT,
    HTTP_HTTP,
    SLASH_AFTER_HTTP,
    MAJOR_DIGIT,
    DOT_IN_DIGIT,
    MINOR_DIGIT,
    SPACE_AFTER_DIGIT,

    LINE_DONE
};

enum HTTP_PARSE_REQUEST_BODY_STATE_T
{
    HEADER_START,
    KEY,
    KEY_END,
    COLON_AFTER_KEY,
    SPACE_AFTER_COLON,
    VALUE_START,
    SPACE_AFTER_VALUE,

    CR,
    CRLF,
    CRLFCR
};

enum HTTP_METHOD_T
{
    METHOD_GET,
    METHOD_POST,
    METHOD_HEAD,
    METHOD_UNKNOWN
};

enum HTTP_PARSE_ERROR_T
{
    HTTP_PARSE_INVALID_METHOD,
    HTTP_PARSE_INVALID_URI,
    HTTP_PARSE_INVALID_HTTP_VERSION,
    HTTP_PARSE_INVALID_REQUEST_LINE
};

#endif //LEPTSERVER_LEPTDEFINITION_H
